name: deploy-dev

on:
  workflow_run:
    workflows: ["run-tests"]
    branches: ["develop"]
    types:
      - completed

  # Run workflow manually if required
  workflow_dispatch:

env:
  ANGULAR_DIST_LOCATION: '${{ github.workspace }}/src/dist/hello-world/'
    
defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      # Makes source code accessible via $github.workspace
      - name: 'Check out source code'
        uses: actions/checkout@v2
        
      - name: 'Install node'
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: 'Fetch dependencies'
        run: npm ci

      - name: 'Build'
        run: npm run build --configuration=production

      # Authentication
      # Set up the following secrets in your repository: AZURE_CREDENTIALS
      # For details see https://docs.microsoft.com/en-us/azure/developer/github/connect-from-azure
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Static Web App
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_DEPLOY_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations
          action: 'upload'
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: '${{ env.ANGULAR_DIST_LOCATION }}' # App source code path
          ###### End of Repository/Build Configurations ######

      # - name: Upload to blob storage
      #   uses: azure/CLI@v1
      #   with:
      #     inlineScript: |
      #         az storage blob upload-batch \
      #         --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT_NAME }} \
      #         --source ${{ env.ANGULAR_DIST_LOCATION }} \
      #         --destination '$web' \
      #         --auth-mode key \
      #         --overwrite true \

      - name: 'Logout from Azure'
        run: |
              az logout
        if: always()